import { Footer } from "@/components/Footer";
import { NavBar } from "@/components/Navbar";
import type { Metadata } from "next";
import { Poppins, Tiro_Bangla } from "next/font/google";
import "./globals.css";

// Import Tiro Bangla
const tiroBangla = Tiro_Bangla({
  variable: "--font-tiro-bangla",
  subsets: ["bengali", "latin"],
  weight: ["400"],
});

// Import Poppins
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dr. Md. Saidur Rahman",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tiroBangla.variable} ${poppins.variable} antialiased`}
      >
        <NavBar />
        <div className="bg-[#34344e] py-12">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
